name: Test PowerShell on Ubuntu
on: push

jobs:
  pester-tests:
    name: Perform pester tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install required PowerShell modules
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module Az.Resources -ErrorAction Stop
          Install-Module Az.App -ErrorAction Stop
      - name: run tests
        shell: pwsh
        run: |
          Invoke-Pester ../*.tests.ps1 -Passthru | Export-CliXml -Path pester.tests.xml
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu-Unit-Tests
          path: pester.tests.xml
    if: ${{ always() }}
